rating_phrases = [
    'what is the rating',
    'how is it rated',
    'rating of',
    'show me top rated',
    'top movies',
    'best movies',
    'highest rated',
    'rate this movie',
    'movie ratings',
    'ratings for',
    'how many stars',
    'star rating',
    'rated well',
    'good movies',
    'movie score',
    'score of',
    'imdb rated',
    'rotten tomatoes rated',
    'critics rating',
    'audience rating',
    'rated PG',
    'rated R',
    'family friendly',
    'for adults',
    'what’s its score',
    'how good is',
    'is it any good',
    'worth watching',
    'recommend any good',
    'must watch',
    'should I watch',
    'give me something rated',
    'acclaimed movies',
    'award-winning',
    'box office hits',
    'popular movies',
    'trending movies',
    'movies like',
    'similar to',
    'give me movies with a rating higher than',
    'movies over',
    'under rated',
    'over rated',
    'rated movie',
    'great movies',
    'poorly rated',
    'highly rated',
    'low ratings',
    'average rating',
    'film rating',
    'rating guide',
    'rated for children',
    'teen rating',
    'adult films',
    'mature audiences',
    'rating system',
    'movie recommendation',
    'recommended films',
    'editor’s choice',
    'critically acclaimed'
];
templates_keyword_movies_with_rating = [
    "Explore the gripping narrative of {title}, which has captivated audiences with its stellar rating of {rating} stars.",
    "Don’t miss out on {title}, a film that seamlessly blends drama and suspense, earning a formidable {rating} star rating.",
    "Step into the world of {title}, a film that has garnered a {rating} star rating for its extraordinary narrative and visual excellence.",
    "Celebrate cinematic brilliance with {title}, highly rated at {rating} stars and a must-watch for enthusiasts.",
    "Delve into the thought-provoking themes of {title}, a film that challenges norms and boasts a rating of {rating} stars.",
    "Rediscover the magic of the silver screen with {title} rated {rating} stars—a true film masterpiece.",
    "Unlock the secrets of {title}, a critically acclaimed film that has achieved a {rating} star rating.",
    "Experience the thrill and drama of {title}, a standout film with a remarkable {rating} stars in its cadre.",
    "Join the adventure in {title}, an epic journey rated {rating} stars that will keep you on the edge of your seat.",
    "Immerse yourself in the masterful storytelling of {title}, which has enchanted audiences and critics alike, achieving {rating} stars.",
    "Witness the gripping tale of survival in {title}, a profound cinematic experience rated {rating} stars.",
    "Be captivated by the unique charm and wit of {title}, a film that has earned a well-deserved {rating} stars.",
    "See why critics are raving about {title}, a powerhouse of a film with a compelling {rating} star rating.",
    "Embark on a cinematic odyssey with {title}, where every scene is a masterpiece, meriting {rating} stars.",
    "Feel the intensity of {title}, a film that resonates with a strong {rating} star rating due to its powerful narrative.",
    "Discover why {title} has become a fan favorite, scoring an impressive {rating} stars for its engaging plot and characters.",
    "Get lost in the intricate world of {title}, a film that combines art and emotion, and boasts a rating of {rating} stars.",
    "Enjoy the compelling character arcs in {title}, a film that has won hearts and a {rating} star rating.",
    "Revel in the stunning visuals and gripping storyline of {title}, a film that has rightfully earned {rating} stars.",
    "Challenge your perceptions with {title}, a film that has not only entertained but also enlightened, securing {rating} stars."
];
templates_movies_with_year = [
    "Enjoy the enchanting melodies and vibrant scenes of {title}, a film that captures the essence of {year} cinema.",
    "Don’t miss {title} from {year}, an unforgettable journey that blends humor and drama seamlessly.",
    "Discover the charm of {title}, a {year} film that celebrates unique stories and captivating performances.",
    "Lose yourself in the romantic allure of {title}, a standout {year} film that's a must-see for any movie lover.",
    "Experience the emotional rollercoaster of {title}, a film from {year} that will leave you discussing it for days.",
    "Relive the touching moments of {title}, a powerful {year} drama that explores deep and resonant themes.",
    "See {title} and dive into the world of {year}, where cinema meets deep storytelling and remarkable characters.",
    "Catch the critically acclaimed {title}, a {year} film that engages and inspires with its powerful narrative.",
    "Step back to {year} with {title}, a film that redefines the boundaries of cinema with its innovative style.",
    "Be swept off your feet by the whimsical and heartfelt story of {title}, a true {year} cinematic gem.",
    "Take a trip through the emotional landscape of {title}, a {year} film that is as thought-provoking as it is entertaining.",
    "Watch {title} and explore the nuances of love and life in this compelling {year} masterpiece.",
    "Unpack the layers of complex relationships in {title}, a film from {year} that's rich with emotion and drama.",
    "Embark on a journey of self-discovery with {title}, a poignant {year} story that resonates with audiences.",
    "Celebrate the joys and trials of life in {title}, a beautifully crafted film from {year}.",
    "Treat yourself to the delightful story of {title}, where {year} filmmaking shines with originality and grace.",
    "Escape into the cinematic world of {title}, a {year} movie that blends fantasy and reality in a mesmerizing spectacle.",
    "Get inspired by the innovative and daring narrative of {title}, a hallmark film of {year}.",
    "Indulge in the dramatic and picturesque tale of {title}, a film that stands out in {year}'s cinematic landscape.",
    "Witness the evocative and timeless story told in {title}, a must-watch masterpiece from {year}."
];
templates_movies_year_genres = [
    "Discover the charms of {title} ({year}), a delightful blend of {genres} that promises to entertain and amaze.",
    "Step into the eclectic world of {title} ({year}), where genres like {genres} mingle to create a uniquely entertaining experience.",
    "Don't miss {title} ({year}), a perfect example of how {genres} can come together to weave a captivating narrative.",
    "Experience the thrill and laughter in {title} ({year}), a film that masterfully combines the elements of {genres}.",
    "Explore the depths of {title} ({year}), where {genres} converge to challenge and intrigue its audience.",
    "Be captivated by the story of {title} ({year}), where {genres} blend seamlessly to offer a rich cinematic journey.",
    "Revel in the cinematic brilliance of {title} ({year}), a film that celebrates the fusion of {genres} with style and substance.",
    "Enjoy the unique mixture of humor and fear in {title} ({year}), an exemplary showcase of {genres} at their best.",
    "Immerse yourself in the innovative narrative of {title} ({year}), which skillfully combines {genres} for an unforgettable film experience.",
    "Celebrate the creative interplay of {title} ({year}), where {genres} are intertwined to produce a truly mesmerizing film.",
    "Dive into the action-packed world of {title} ({year}), where {genres} collide in an explosive blend of excitement and suspense.",
    "Witness the dramatic unfolding in {title} ({year}), a film that masterfully interlaces {genres} to captivate its audience.",
    "Uncover the hidden secrets in {title} ({year}), a {genres} thriller that keeps you guessing until the very end.",
    "Experience the heartfelt journey of {title} ({year}), a touching {genres} story that resonates with audiences worldwide.",
    "Engage with the vibrant characters of {title} ({year}), a {genres} saga that celebrates diversity and complexity.",
    "Relish the comedic genius of {title} ({year}), where {genres} meet to deliver laughs and profound insights alike.",
    "Navigate the twists and turns of {title} ({year}), a {genres} film that challenges perceptions and entertains thoroughly.",
    "Admire the artistic flair of {title} ({year}), a {genres} film that dazzles with its visual and narrative creativity.",
    "Get swept away by the romance of {title} ({year}), where {genres} blend to craft a love story for the ages.",
    "Embrace the suspense in {title} ({year}), a thrilling {genres} adventure that keeps your heart racing from start to finish."
]